### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by caseykelso**

### CODE REVIEW

**Comment by gbmhunter** [comment]
Thanks for the improvements @caseykelso !

**Comment by gbmhunter** [comment]
Woops, I think this MR broke the build, see https://github.com/gbmhunter/CppLinuxSerial/issues/53. I'll add `#include <asm/termbits.h>` back into the main header file, unless @caseykelso you have a good reason to keep it removed? (and a different fix?).

**Comment by caseykelso** [comment]
Yes there was reason to move it, as the include conflicts with libuv.

I'll put up another patch, where did it break?

**Comment by gbmhunter** [comment]
See the issue https://github.com/gbmhunter/CppLinuxSerial/issues/53. I can't get it to break when building under WSL 2 with Ubuntu, so something is different between my environment and the other persons.

I added back in `termios.h` instead of `asm/termbits.h` as documentation online suggests that is the correct header to include to get the `speed_t` definition.

**Pull request merged**
